[[main]]
identifier = "posts"
name = "Posts"
weight = 10
hasChildren = true

[[main]]
identifier = "java-journey"
name = "Java Journey"
pageRef = "posts/java-journey"
parent = "posts"
weight = 11

[[main]]
name = "Projects"
pageRef = "projects"
weight = 20

[[main]]
name = "About"
pageRef = "about"
weight = 30
